version: "0.1"
services:
  database:
    image: postgres:12
    container_name: postgres12
    restart: always
    environment:
       postgres_user: root
       postgres_password: toor
    ports:
      - 5432:5432
    volumes:
      - "/home/ali/container/postgres/data:/var/lib/postgresql/data"
    
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
